name: fasila
description: "FASILA's Mobile Application"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^5.0.0-release-candidate-9.2.1
  getwidget: ^4.0.0
  flutter_screenutil: ^5.9.3
  syncfusion_flutter_gauges: ^27.1.52
  percent_indicator: ^4.2.3
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  http:
  web_socket_channel: ^3.0.1
  flutter_dotenv: ^5.2.1
  connectivity_plus: ^5.0.2
  firebase_messaging: ^15.1.5
  firebase_core: ^3.8.0
  firebase_analytics: ^11.3.5
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.3.4
  syncfusion_flutter_charts: ^27.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env
